// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFhmCxVqRZ-J-grvV8Xf7lyHUyCiJ8jFA',
    appId: '1:821032240777:web:8d38b01b35f15b2e6ea858',
    messagingSenderId: '821032240777',
    projectId: 'carthageapp-fc62a',
    authDomain: 'carthageapp-fc62a.firebaseapp.com',
    storageBucket: 'carthageapp-fc62a.firebasestorage.app',
    measurementId: 'G-4K7LEGGB5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFLw-dkoYGjZHWoEN-CuvDRy1pQAEFucM',
    appId: '1:821032240777:android:0a1558f921c581786ea858',
    messagingSenderId: '821032240777',
    projectId: 'carthageapp-fc62a',
    storageBucket: 'carthageapp-fc62a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbja6BeX9bFxHWQF4yMn466UuK0ER_BJA',
    appId: '1:821032240777:ios:2e5daa473f3017cf6ea858',
    messagingSenderId: '821032240777',
    projectId: 'carthageapp-fc62a',
    storageBucket: 'carthageapp-fc62a.firebasestorage.app',
    iosBundleId: 'com.example.carthageStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbja6BeX9bFxHWQF4yMn466UuK0ER_BJA',
    appId: '1:821032240777:ios:2e5daa473f3017cf6ea858',
    messagingSenderId: '821032240777',
    projectId: 'carthageapp-fc62a',
    storageBucket: 'carthageapp-fc62a.firebasestorage.app',
    iosBundleId: 'com.example.carthageStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFhmCxVqRZ-J-grvV8Xf7lyHUyCiJ8jFA',
    appId: '1:821032240777:web:ce12646a88bf44906ea858',
    messagingSenderId: '821032240777',
    projectId: 'carthageapp-fc62a',
    authDomain: 'carthageapp-fc62a.firebaseapp.com',
    storageBucket: 'carthageapp-fc62a.firebasestorage.app',
    measurementId: 'G-YXP6NGH2HG',
  );

}